Feature/interviews
ralitsadineva/smart-hire pull request #11
Opened 2023-08-03 07:20 UTC by ralitsadineva

Interview feedback, status application, statistics, search

2023-08-03 13:52 UTC, ilian-iliev-io requested changes

2023-08-03 13:52 UTC, ilian-iliev-io commented on services/positions.py
> +    return [positions_db.get(id)['title'], positions_db.get(id)['description']]
position = positions_db.get(id)

2023-08-03 13:52 UTC, ilian-iliev-io commented on services/users.py
> +    signature, company = users_db.get(id)['signature'], users_db.get(id)['company']
.

2023-08-03 13:52 UTC, ilian-iliev-io commented on templates/candidate.html
> +            <p class="mt-3 fw-semibold border-top border-success-subtle">Declined because of {% if candidate['decline_reason'] == '1' %}the company culture or environment{% elif candidate['decline_re
DECLINE_1 = '1'
DECLINE_2 = '2'
DECINE_REASONS = { DECLINE_1:  'test 1', DECLINE_2:  'test 2'} 

def get_decline_reason_string(reason):
     return DECINE_REASONS[reason]
     
  {% decline_reason_string %}

2023-08-03 13:52 UTC, ilian-iliev-io commented on templates/candidate.html
> +                    <option value="1">the company culture or environment</option>
dynamic generation

2023-08-03 13:52 UTC, ilian-iliev-io commented on templates/interview.html
> +                                <option {% if interview and interview['score']==1 %}selected{% endif %} value="1">1</option>
loop

2023-08-04 08:24 UTC, ilian-iliev-io approved these changes

2023-08-04 08:25 UTC, ilian6806 approved these changes

2023-08-04 08:26 UTC, merged